import type { PracticeExercise } from "../courses";

export const MODULE_2_CHALLENGES: Record<string, PracticeExercise[]> = {
  "conditionals-logic": [
    {
      id: "conditionals-logic-p1",
      title: "Problem 1: FizzBuzz Router 1",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `classify_number_1(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_1(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-1",
          name: "Divisible by 15",
          inputCode: "classify_number_1(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-1",
          name: "Divisible by 3",
          inputCode: "classify_number_1(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-1",
          name: "Neither",
          inputCode: "classify_number_1(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_1(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p2",
      title: "Problem 2: FizzBuzz Router 2",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `classify_number_2(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_2(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-2",
          name: "Divisible by 15",
          inputCode: "classify_number_2(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-2",
          name: "Divisible by 3",
          inputCode: "classify_number_2(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-2",
          name: "Neither",
          inputCode: "classify_number_2(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_2(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p3",
      title: "Problem 3: FizzBuzz Router 3",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `classify_number_3(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_3(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-3",
          name: "Divisible by 15",
          inputCode: "classify_number_3(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-3",
          name: "Divisible by 3",
          inputCode: "classify_number_3(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-3",
          name: "Neither",
          inputCode: "classify_number_3(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_3(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p4",
      title: "Problem 4: FizzBuzz Router 4",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `classify_number_4(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_4(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-4",
          name: "Divisible by 15",
          inputCode: "classify_number_4(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-4",
          name: "Divisible by 3",
          inputCode: "classify_number_4(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-4",
          name: "Neither",
          inputCode: "classify_number_4(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_4(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p5",
      title: "Problem 5: FizzBuzz Router 5",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `classify_number_5(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_5(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-5",
          name: "Divisible by 15",
          inputCode: "classify_number_5(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-5",
          name: "Divisible by 3",
          inputCode: "classify_number_5(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-5",
          name: "Neither",
          inputCode: "classify_number_5(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_5(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p6",
      title: "Problem 6: FizzBuzz Router 6",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `classify_number_6(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_6(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-6",
          name: "Divisible by 15",
          inputCode: "classify_number_6(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-6",
          name: "Divisible by 3",
          inputCode: "classify_number_6(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-6",
          name: "Neither",
          inputCode: "classify_number_6(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_6(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p7",
      title: "Problem 7: FizzBuzz Router 7",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `classify_number_7(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_7(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-7",
          name: "Divisible by 15",
          inputCode: "classify_number_7(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-7",
          name: "Divisible by 3",
          inputCode: "classify_number_7(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-7",
          name: "Neither",
          inputCode: "classify_number_7(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_7(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p8",
      title: "Problem 8: FizzBuzz Router 8",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `classify_number_8(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_8(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-8",
          name: "Divisible by 15",
          inputCode: "classify_number_8(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-8",
          name: "Divisible by 3",
          inputCode: "classify_number_8(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-8",
          name: "Neither",
          inputCode: "classify_number_8(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_8(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p9",
      title: "Problem 9: FizzBuzz Router 9",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `classify_number_9(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_9(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-9",
          name: "Divisible by 15",
          inputCode: "classify_number_9(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-9",
          name: "Divisible by 3",
          inputCode: "classify_number_9(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-9",
          name: "Neither",
          inputCode: "classify_number_9(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_9(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p10",
      title: "Problem 10: FizzBuzz Router 10",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `classify_number_10(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_10(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-10",
          name: "Divisible by 15",
          inputCode: "classify_number_10(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-10",
          name: "Divisible by 3",
          inputCode: "classify_number_10(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-10",
          name: "Neither",
          inputCode: "classify_number_10(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_10(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p11",
      title: "Problem 11: FizzBuzz Router 11",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `classify_number_11(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_11(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-11",
          name: "Divisible by 15",
          inputCode: "classify_number_11(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-11",
          name: "Divisible by 3",
          inputCode: "classify_number_11(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-11",
          name: "Neither",
          inputCode: "classify_number_11(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_11(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p12",
      title: "Problem 12: FizzBuzz Router 12",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `classify_number_12(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_12(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-12",
          name: "Divisible by 15",
          inputCode: "classify_number_12(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-12",
          name: "Divisible by 3",
          inputCode: "classify_number_12(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-12",
          name: "Neither",
          inputCode: "classify_number_12(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_12(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p13",
      title: "Problem 13: FizzBuzz Router 13",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `classify_number_13(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_13(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-13",
          name: "Divisible by 15",
          inputCode: "classify_number_13(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-13",
          name: "Divisible by 3",
          inputCode: "classify_number_13(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-13",
          name: "Neither",
          inputCode: "classify_number_13(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_13(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p14",
      title: "Problem 14: FizzBuzz Router 14",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `classify_number_14(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_14(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-14",
          name: "Divisible by 15",
          inputCode: "classify_number_14(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-14",
          name: "Divisible by 3",
          inputCode: "classify_number_14(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-14",
          name: "Neither",
          inputCode: "classify_number_14(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_14(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p15",
      title: "Problem 15: FizzBuzz Router 15",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `classify_number_15(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_15(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-15",
          name: "Divisible by 15",
          inputCode: "classify_number_15(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-15",
          name: "Divisible by 3",
          inputCode: "classify_number_15(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-15",
          name: "Neither",
          inputCode: "classify_number_15(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_15(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p16",
      title: "Problem 16: FizzBuzz Router 16",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `classify_number_16(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_16(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-16",
          name: "Divisible by 15",
          inputCode: "classify_number_16(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-16",
          name: "Divisible by 3",
          inputCode: "classify_number_16(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-16",
          name: "Neither",
          inputCode: "classify_number_16(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_16(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p17",
      title: "Problem 17: FizzBuzz Router 17",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `classify_number_17(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_17(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-17",
          name: "Divisible by 15",
          inputCode: "classify_number_17(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-17",
          name: "Divisible by 3",
          inputCode: "classify_number_17(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-17",
          name: "Neither",
          inputCode: "classify_number_17(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_17(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p18",
      title: "Problem 18: FizzBuzz Router 18",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `classify_number_18(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_18(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-18",
          name: "Divisible by 15",
          inputCode: "classify_number_18(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-18",
          name: "Divisible by 3",
          inputCode: "classify_number_18(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-18",
          name: "Neither",
          inputCode: "classify_number_18(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_18(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p19",
      title: "Problem 19: FizzBuzz Router 19",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `classify_number_19(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_19(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-19",
          name: "Divisible by 15",
          inputCode: "classify_number_19(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-19",
          name: "Divisible by 3",
          inputCode: "classify_number_19(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-19",
          name: "Neither",
          inputCode: "classify_number_19(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_19(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    },
    {
      id: "conditionals-logic-p20",
      title: "Problem 20: FizzBuzz Router 20",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `classify_number_20(n)` that returns 'FizzBuzz' if n is divisible by 15, 'Fizz' if divisible by 3, 'Buzz' if divisible by 5, or str(n) otherwise.",
      starterCode: "def classify_number_20(n):\n    # Write your solution here\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)\n",
      testCases: [
        {
          id: "conditionals-logic-tc1-20",
          name: "Divisible by 15",
          inputCode: "classify_number_20(30)",
          expectedOutput: "FizzBuzz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc2-20",
          name: "Divisible by 3",
          inputCode: "classify_number_20(9)",
          expectedOutput: "Fizz",
          isHidden: false,
        },
        {
          id: "conditionals-logic-tc3-20",
          name: "Neither",
          inputCode: "classify_number_20(7)",
          expectedOutput: "7",
          isHidden: true,
        }
      ],
      hint: "Check n % 15 == 0 first before n % 3 or n % 5.",
      solution: "def classify_number_20(n):\n    if n % 15 == 0: return 'FizzBuzz'\n    if n % 3 == 0: return 'Fizz'\n    if n % 5 == 0: return 'Buzz'\n    return str(n)",
    }
  ],
  "loop-control-nested": [
    {
      id: "loop-control-nested-p1",
      title: "Problem 1: Diagonal Matrix Sum 1",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `sum_matrix_diagonals_1(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_1(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-1",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_1([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-1",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_1([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-1",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_1([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_1(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p2",
      title: "Problem 2: Diagonal Matrix Sum 2",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `sum_matrix_diagonals_2(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_2(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-2",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_2([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-2",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_2([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-2",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_2([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_2(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p3",
      title: "Problem 3: Diagonal Matrix Sum 3",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `sum_matrix_diagonals_3(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_3(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-3",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_3([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-3",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_3([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-3",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_3([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_3(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p4",
      title: "Problem 4: Diagonal Matrix Sum 4",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `sum_matrix_diagonals_4(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_4(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-4",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_4([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-4",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_4([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-4",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_4([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_4(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p5",
      title: "Problem 5: Diagonal Matrix Sum 5",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `sum_matrix_diagonals_5(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_5(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-5",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_5([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-5",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_5([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-5",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_5([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_5(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p6",
      title: "Problem 6: Diagonal Matrix Sum 6",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `sum_matrix_diagonals_6(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_6(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-6",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_6([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-6",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_6([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-6",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_6([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_6(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p7",
      title: "Problem 7: Diagonal Matrix Sum 7",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `sum_matrix_diagonals_7(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_7(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-7",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_7([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-7",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_7([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-7",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_7([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_7(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p8",
      title: "Problem 8: Diagonal Matrix Sum 8",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `sum_matrix_diagonals_8(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_8(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-8",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_8([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-8",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_8([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-8",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_8([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_8(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p9",
      title: "Problem 9: Diagonal Matrix Sum 9",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `sum_matrix_diagonals_9(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_9(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-9",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_9([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-9",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_9([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-9",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_9([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_9(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p10",
      title: "Problem 10: Diagonal Matrix Sum 10",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `sum_matrix_diagonals_10(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_10(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-10",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_10([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-10",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_10([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-10",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_10([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_10(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p11",
      title: "Problem 11: Diagonal Matrix Sum 11",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `sum_matrix_diagonals_11(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_11(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-11",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_11([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-11",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_11([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-11",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_11([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_11(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p12",
      title: "Problem 12: Diagonal Matrix Sum 12",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `sum_matrix_diagonals_12(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_12(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-12",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_12([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-12",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_12([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-12",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_12([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_12(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p13",
      title: "Problem 13: Diagonal Matrix Sum 13",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `sum_matrix_diagonals_13(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_13(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-13",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_13([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-13",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_13([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-13",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_13([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_13(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p14",
      title: "Problem 14: Diagonal Matrix Sum 14",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `sum_matrix_diagonals_14(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_14(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-14",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_14([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-14",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_14([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-14",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_14([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_14(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p15",
      title: "Problem 15: Diagonal Matrix Sum 15",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `sum_matrix_diagonals_15(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_15(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-15",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_15([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-15",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_15([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-15",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_15([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_15(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p16",
      title: "Problem 16: Diagonal Matrix Sum 16",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `sum_matrix_diagonals_16(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_16(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-16",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_16([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-16",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_16([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-16",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_16([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_16(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p17",
      title: "Problem 17: Diagonal Matrix Sum 17",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `sum_matrix_diagonals_17(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_17(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-17",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_17([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-17",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_17([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-17",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_17([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_17(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p18",
      title: "Problem 18: Diagonal Matrix Sum 18",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `sum_matrix_diagonals_18(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_18(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-18",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_18([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-18",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_18([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-18",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_18([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_18(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p19",
      title: "Problem 19: Diagonal Matrix Sum 19",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `sum_matrix_diagonals_19(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_19(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-19",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_19([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-19",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_19([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-19",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_19([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_19(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    },
    {
      id: "loop-control-nested-p20",
      title: "Problem 20: Diagonal Matrix Sum 20",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `sum_matrix_diagonals_20(matrix)` that computes the sum of the primary diagonal elements (`matrix[i][i]`) of an NxN 2D list.",
      starterCode: "def sum_matrix_diagonals_20(matrix):\n    # Write your solution here\n    return sum(matrix[i][i] for i in range(len(matrix)))\n",
      testCases: [
        {
          id: "loop-control-nested-tc1-20",
          name: "3x3 Matrix",
          inputCode: "sum_matrix_diagonals_20([[1,2,3],[4,5,6],[7,8,9]])",
          expectedOutput: "15",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc2-20",
          name: "2x2 Matrix",
          inputCode: "sum_matrix_diagonals_20([[10,20],[30,40]])",
          expectedOutput: "50",
          isHidden: false,
        },
        {
          id: "loop-control-nested-tc3-20",
          name: "1x1 Matrix",
          inputCode: "sum_matrix_diagonals_20([[99]])",
          expectedOutput: "99",
          isHidden: true,
        }
      ],
      hint: "Loop with index i from 0 to len(matrix)-1 and sum matrix[i][i].",
      solution: "def sum_matrix_diagonals_20(matrix):\n    return sum(matrix[i][i] for i in range(len(matrix)))",
    }
  ],
  "comprehensions": [
    {
      id: "comprehensions-p1",
      title: "Problem 1: Even Squares Filter 1",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `square_evens_1(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_1(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-1",
          name: "Mixed Numbers",
          inputCode: "square_evens_1([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-1",
          name: "All Odds",
          inputCode: "square_evens_1([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-1",
          name: "All Evens",
          inputCode: "square_evens_1([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_1(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p2",
      title: "Problem 2: Even Squares Filter 2",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `square_evens_2(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_2(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-2",
          name: "Mixed Numbers",
          inputCode: "square_evens_2([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-2",
          name: "All Odds",
          inputCode: "square_evens_2([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-2",
          name: "All Evens",
          inputCode: "square_evens_2([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_2(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p3",
      title: "Problem 3: Even Squares Filter 3",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `square_evens_3(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_3(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-3",
          name: "Mixed Numbers",
          inputCode: "square_evens_3([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-3",
          name: "All Odds",
          inputCode: "square_evens_3([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-3",
          name: "All Evens",
          inputCode: "square_evens_3([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_3(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p4",
      title: "Problem 4: Even Squares Filter 4",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `square_evens_4(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_4(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-4",
          name: "Mixed Numbers",
          inputCode: "square_evens_4([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-4",
          name: "All Odds",
          inputCode: "square_evens_4([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-4",
          name: "All Evens",
          inputCode: "square_evens_4([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_4(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p5",
      title: "Problem 5: Even Squares Filter 5",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `square_evens_5(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_5(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-5",
          name: "Mixed Numbers",
          inputCode: "square_evens_5([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-5",
          name: "All Odds",
          inputCode: "square_evens_5([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-5",
          name: "All Evens",
          inputCode: "square_evens_5([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_5(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p6",
      title: "Problem 6: Even Squares Filter 6",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `square_evens_6(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_6(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-6",
          name: "Mixed Numbers",
          inputCode: "square_evens_6([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-6",
          name: "All Odds",
          inputCode: "square_evens_6([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-6",
          name: "All Evens",
          inputCode: "square_evens_6([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_6(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p7",
      title: "Problem 7: Even Squares Filter 7",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `square_evens_7(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_7(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-7",
          name: "Mixed Numbers",
          inputCode: "square_evens_7([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-7",
          name: "All Odds",
          inputCode: "square_evens_7([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-7",
          name: "All Evens",
          inputCode: "square_evens_7([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_7(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p8",
      title: "Problem 8: Even Squares Filter 8",
      difficulty: "Easy",
      points: 10,
      task: "Write a function `square_evens_8(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_8(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-8",
          name: "Mixed Numbers",
          inputCode: "square_evens_8([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-8",
          name: "All Odds",
          inputCode: "square_evens_8([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-8",
          name: "All Evens",
          inputCode: "square_evens_8([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_8(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p9",
      title: "Problem 9: Even Squares Filter 9",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `square_evens_9(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_9(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-9",
          name: "Mixed Numbers",
          inputCode: "square_evens_9([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-9",
          name: "All Odds",
          inputCode: "square_evens_9([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-9",
          name: "All Evens",
          inputCode: "square_evens_9([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_9(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p10",
      title: "Problem 10: Even Squares Filter 10",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `square_evens_10(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_10(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-10",
          name: "Mixed Numbers",
          inputCode: "square_evens_10([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-10",
          name: "All Odds",
          inputCode: "square_evens_10([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-10",
          name: "All Evens",
          inputCode: "square_evens_10([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_10(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p11",
      title: "Problem 11: Even Squares Filter 11",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `square_evens_11(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_11(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-11",
          name: "Mixed Numbers",
          inputCode: "square_evens_11([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-11",
          name: "All Odds",
          inputCode: "square_evens_11([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-11",
          name: "All Evens",
          inputCode: "square_evens_11([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_11(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p12",
      title: "Problem 12: Even Squares Filter 12",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `square_evens_12(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_12(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-12",
          name: "Mixed Numbers",
          inputCode: "square_evens_12([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-12",
          name: "All Odds",
          inputCode: "square_evens_12([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-12",
          name: "All Evens",
          inputCode: "square_evens_12([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_12(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p13",
      title: "Problem 13: Even Squares Filter 13",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `square_evens_13(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_13(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-13",
          name: "Mixed Numbers",
          inputCode: "square_evens_13([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-13",
          name: "All Odds",
          inputCode: "square_evens_13([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-13",
          name: "All Evens",
          inputCode: "square_evens_13([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_13(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p14",
      title: "Problem 14: Even Squares Filter 14",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `square_evens_14(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_14(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-14",
          name: "Mixed Numbers",
          inputCode: "square_evens_14([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-14",
          name: "All Odds",
          inputCode: "square_evens_14([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-14",
          name: "All Evens",
          inputCode: "square_evens_14([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_14(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p15",
      title: "Problem 15: Even Squares Filter 15",
      difficulty: "Medium",
      points: 20,
      task: "Write a function `square_evens_15(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_15(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-15",
          name: "Mixed Numbers",
          inputCode: "square_evens_15([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-15",
          name: "All Odds",
          inputCode: "square_evens_15([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-15",
          name: "All Evens",
          inputCode: "square_evens_15([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_15(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p16",
      title: "Problem 16: Even Squares Filter 16",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `square_evens_16(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_16(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-16",
          name: "Mixed Numbers",
          inputCode: "square_evens_16([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-16",
          name: "All Odds",
          inputCode: "square_evens_16([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-16",
          name: "All Evens",
          inputCode: "square_evens_16([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_16(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p17",
      title: "Problem 17: Even Squares Filter 17",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `square_evens_17(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_17(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-17",
          name: "Mixed Numbers",
          inputCode: "square_evens_17([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-17",
          name: "All Odds",
          inputCode: "square_evens_17([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-17",
          name: "All Evens",
          inputCode: "square_evens_17([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_17(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p18",
      title: "Problem 18: Even Squares Filter 18",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `square_evens_18(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_18(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-18",
          name: "Mixed Numbers",
          inputCode: "square_evens_18([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-18",
          name: "All Odds",
          inputCode: "square_evens_18([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-18",
          name: "All Evens",
          inputCode: "square_evens_18([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_18(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p19",
      title: "Problem 19: Even Squares Filter 19",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `square_evens_19(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_19(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-19",
          name: "Mixed Numbers",
          inputCode: "square_evens_19([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-19",
          name: "All Odds",
          inputCode: "square_evens_19([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-19",
          name: "All Evens",
          inputCode: "square_evens_19([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_19(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    },
    {
      id: "comprehensions-p20",
      title: "Problem 20: Even Squares Filter 20",
      difficulty: "Hard",
      points: 30,
      task: "Write a function `square_evens_20(numbers)` that uses a list comprehension to return squares of only the even integers in the given list.",
      starterCode: "def square_evens_20(numbers):\n    # Write your solution here\n    return [x ** 2 for x in numbers if x % 2 == 0]\n",
      testCases: [
        {
          id: "comprehensions-tc1-20",
          name: "Mixed Numbers",
          inputCode: "square_evens_20([1, 2, 3, 4, 5, 6])",
          expectedOutput: "[4, 16, 36]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc2-20",
          name: "All Odds",
          inputCode: "square_evens_20([1, 3, 5])",
          expectedOutput: "[]",
          isHidden: false,
        },
        {
          id: "comprehensions-tc3-20",
          name: "All Evens",
          inputCode: "square_evens_20([2, 10])",
          expectedOutput: "[4, 100]",
          isHidden: true,
        }
      ],
      hint: "Use [x ** 2 for x in numbers if x % 2 == 0].",
      solution: "def square_evens_20(numbers):\n    return [x ** 2 for x in numbers if x % 2 == 0]",
    }
  ],
};
