export const siteConfig = {
  name: "Amol Shukla — AI Developer & Trainer",
  authorName: "Amol Shukla",
  username: "amolshukla",
  description:
    "Amol Shukla is an AI Developer, Trainer, and Agentic AI Expert building agentic AI systems, training on LLMs and generative AI, and developing production software with Python. Explore his projects, experience, and technical blog.",
  url: "https://www.amolshukla.online",
  links: {
    twitter: "https://x.com/amolshukla",
    github: "https://github.com/amolshukla",
    templateRepo: "https://github.com/amolshukla25/PORTFFOLIO",
    resume: "https://drive.google.com/file/d/1BiUASo5wgZyJ2NFJwm8wmsQFNx09_Aov/view?usp=sharing",
  },
  ogImage: "/og.png",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  appleIcon: "/apple-touch-icon.png",
  keywords: [
    "Amol Shukla",
    "AI Developer",
    "AI Trainer",
    "Agentic AI",
    "Agentic AI Expert",
    "Applied AI Engineer",
    "AI Engineer",
    "Generative AI",
    "LLM",
    "Python Developer",
    "Machine Learning",
    "Full Stack Developer",
    "Software Engineer",
    "Data Engineering",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "Databricks",
    "AI Startups",
    "Software Development",
    "Web Developer",
    "Backend Developer",
    "Frontend Developer",
    "Tech Portfolio",
  ],
};
