export const siteConfig = {
  name: "Amol shukla - Applied AI Engineer",
  authorName: "Amol shukla",
  username: "amolshukla",
  description:
    "Amol shukla - Applied AI Engineer working at the intersection of AI, data, and scalable software systems. Explore my projects, experience, and contributions in software development and AI.",
  url: "https://amolshukla.xyz",
  links: {
    twitter: "https://x.com/amolshukla",
    github: "https://github.com/amolshukla",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },
  ogImage: "/profile-img.jpg",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Amol shukla",
    "Applied AI Engineer",
    "AI Engineer",
    "Software Engineer",
    "Full Stack Developer",
    "Machine Learning",
    "Data Engineering",
    "UBS",
    "Python Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "Databricks",
    "AI Startups",
    "Software Development",
    "Web Developer",
    "Backend Developer",
    "Frontend Developer",
    "Tech Portfolio",
  ],
};
